##
# Call Shibe Application Configuration
#
#

##
# Example Configuration object.
# (Basically the defaults which can be overridden nicely for environments
#
template: &template
  # Global Conference Room options & defaults
  conference_rooms:
    
    # Enable Multi-number environment
    # If enabled, the join code *and* incoming number are matched
    # This allows join codes to be recycled across different inbound numbers
    # If disabled, the inbound number is disabled, and join codes must be unique.
    multi_number: false

    # Default conference room options
    default_options:
      # Beep on join/leave
      # Can be any of true, false on-join and on-leave
      beep: true

      # Record conferences.
      record: true

      # Trim silence from any recordings.
      trim_silence: true

      # Maximum users connected to a call
      max_participents: 5

      # URL for hold music
      # Use null for default
      wait_audio: null

  welcome_message: Welcome to Call Shibe. Conferencing with WOW!

  # Logging Options
  logging:
    # Log level, may be "debug" , "info", "warning" , "error", "crit" and "fatal"
    level: INFO
    
    # File may be any path (relative to where the application is started)
    # Or `false` for STDOUT
    file: false

  dynamoid:
    namespace: call_shibe

# Development environment.
development:
  <<: *template
  logging:
    level: DEBUG
    file: false

test:
  <<: *template
  logging:
    level: DEBUG
    file: false

# Production
production:
  <<: *template

  i18n:
    welcome_message:
      Welcome to Mr Zen's Conferencing system.
    join_code_prompt:
      Please enter your four digit code. Then press the hash key.

  conference_rooms:
    wait_audio:
     - http://s3.amazonaws.com/call-shibe-assets/default.mp3

  dynamoid:
    namespace: call_shibe_production
